services:
  database:
    image: postgres:16-alpine
    container_name: taskflow_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha_secreta_123
      POSTGRES_DB: taskflow
    ports:
      - "5432:5432"
    networks:
      - taskflow_network

  api:
    image: victordevpbi/taskflow-api:v1
    container_name: taskflow_api
    build: .
    ports:
      - "8000:8000"
    # Damos 5 segundos para o Postgres subir as tabelas do sistema e depois iniciamos
    command: sh -c "sleep 5 && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=database
      - DB_USER=admin
      - DB_PASSWORD=senha_secreta_123
      - DB_NAME=taskflow
      - PYTHONPATH=.
    depends_on:
      - database
    networks:
      - taskflow_network

networks:
  taskflow_network:
    driver: bridge